const menuData = {
    "Non-Veg Kathi Rolls": [
        { name: "Egg Roll", price: 50 },
        { name: "Dbl Egg Roll", price: 70 },
        { name: "Dbl. Egg Cheese Roll", price: 80 },
        { name: "Egg Manchurian Roll", price: 70 },
        { name: "Egg Noodles Roll", price: 70 },
        { name: "Egg Chilli Potato Roll", price: 70 },
        { name: "Egg Pasta Roll", price: 70 },
        { name: "Chicken Roll", price: 90 },
        { name: "Dbl. Chicken Roll", price: 110 },
        { name: "SNL. Egg SNL. Chicken Roll", price: 110 },
        { name: "Dbl. Egg Dbl. Chicken Roll", price: 140 },
        { name: "SNL. Egg Dbl. Chicken Roll", price: 130 },
        { name: "Dbl Egg Single Chicken Roll", price: 120 },
        { name: "Chicken Seekh Roll", price: 90 },
        { name: "Dbl. Chicken Seekh Roll", price: 150 },
        { name: "Malai Chicken Roll", price: 100 },
        { name: "Dbl. Malai Chicken Roll", price: 130 },
        { name: "Chicken Keema Roll", price: 100 },
        { name: "Egg Chicken Keema Roll", price: 120 },
        { name: "Korma Chicken Roll", price: 120 },
        { name: "Chilli Chicken Roll", price: 120 },
        { name: "Butter Chicken Roll", price: 120 },
        { name: "Loaded Chicken Roll", price: 150 },
        { name: "Spl. Chicken Roll", price: 150 },
        { name: "Chicken Tikka Roll", price: 130 },
        { name: "Malai Chicken Tikka Roll", price: 150 }
    ],
    "Veg Kathi Rolls": [
        { name: "Aloo Tikki Roll", price: 50 },
        { name: "Dbl. Aloo Tikki Roll", price: 70 },
        { name: "Aloo Tikki Cheese Roll", price: 70 },
        { name: "Aloo Masala Roll", price: 50 },
        { name: "Aloo Malai Roll", price: 60 },
        { name: "Noodle Roll", price: 50 },
        { name: "Noodle Cheese Roll", price: 70 },
        { name: "Mix Veg. Paneer Roll", price: 70 },
        { name: "Mix Veg. Cheese Roll", price: 70 },
        { name: "Chilli Potato Roll", price: 50 },
        { name: "Chilli Potato Cheese Roll", price: 70 },
        { name: "Honey Chilli Potato Roll", price: 60 },
        { name: "Cheese Roll", price: 50 },
        { name: "Pasta Roll", price: 50 },
        { name: "Cheesy Pasta Roll", price: 70 },
        { name: "Cheese Sweet Corn Roll", price: 70 },
        { name: "Sweet Corn Roll", price: 50 },
        { name: "Manchurian Roll", price: 50 },
        { name: "Manchurian Cheese Roll", price: 70 },
        { name: "Soya Malai Roll", price: 60 },
        { name: "Dbl Soya Malai Roll", price: 90 },
        { name: "Cheesy Soya Malai Roll", price: 80 },
        { name: "Paneer Roll", price: 80 },
        { name: "Dbl. Paneer Roll", price: 100 },
        { name: "Malai Paneer Roll", price: 90 },
        { name: "Dbl. Malai Paneer Roll", price: 110 },
        { name: "Paneer Bhurji Roll", price: 90 },
        { name: "Chilli Paneer Roll", price: 110 },
        { name: "Korma Paneer Roll", price: 110 },
        { name: "Chilli Soya Roll", price: 100 },
        { name: "Korma Soya Roll", price: 100 },
        { name: "Spl. Soya Roll", price: 120 },
        { name: "Schzwan Soya Roll", price: 100 },
        { name: "Achari Soya Roll", price: 100 },
        { name: "Spl. Paneer Roll", price: 130 },
        { name: "Paneer Tikka Roll", price: 120 },
        { name: "Malai Paneer Tikka Roll", price: 130 },
        { name: "Soya Tikka Roll", price: 80 },
        { name: "Soya Malai Tikka Roll", price: 90 }
    ],
    "Tandoori Snacks": [
        { name: "Tandoori Masala Chaap (Half)", price: 90 },
        { name: "Tandoori Masala Chaap (Full)", price: 160 },
        { name: "Soya Malai Chaap (Half)", price: 100 },
        { name: "Soya Malai Chaap (Full)", price: 180 },
        { name: "Paneer Tikka (Half)", price: 140 },
        { name: "Paneer Tikka (Full)", price: 220 },
        { name: "Malai Paneer Tikka (Half)", price: 150 },
        { name: "Malai Paneer Tikka (Full)", price: 240 },
        { name: "Chicken Tikka (Half)", price: 160 },
        { name: "Chicken Tikka (Full)", price: 300 },
        { name: "Chicken Malai Tikka (Half)", price: 170 },
        { name: "Chicken Malai Tikka (Full)", price: 320 },
        { name: "Tandoori Chicken (Half)", price: 220 },
        { name: "Tandoori Chicken (Full)", price: 440 },
        { name: "Chicken Seekh Kabab (Half)", price: 210 },
        { name: "Chicken Seekh Kabab (Full)", price: 420 }
    ],
    "Rice": [
        { name: "Plain Rice (Half)", price: 50 },
        { name: "Plain Rice (Full)", price: 80 },
        { name: "Jeera Rice (Half)", price: 60 },
        { name: "Jeera Rice (Full)", price: 100 },
        { name: "Veg. Fried Rice (Half)", price: 70 },
        { name: "Veg. Fried Rice (Full)", price: 100 },
        { name: "Paneer Fried Rice (Half)", price: 100 },
        { name: "Paneer Fried Rice (Full)", price: 150 },
        { name: "Egg Fried Rice (Half)", price: 70 },
        { name: "Egg Fried Rice (Full)", price: 100 },
        { name: "Chicken Fried Rice (Half)", price: 100 },
        { name: "Chicken Fried Rice (Full)", price: 150 }
    ],
    "Chinese": [
        { name: "Spring Roll", price: 100 },
        { name: "Chilli Potato (Half)", price: 70 },
        { name: "Chilli Potato (Full)", price: 100 },
        { name: "Honey Chilli Potato (Half)", price: 80 },
        { name: "Honey Chilli Potato (Full)", price: 120 },
        { name: "Veg. Manchurian (Half)", price: 100 },
        { name: "Veg. Manchurian (Full)", price: 150 },
        { name: "Chilli Paneer (Half)", price: 130 },
        { name: "Chilli Paneer (Full)", price: 240 },
        { name: "Veg. Noodle (Half)", price: 50 },
        { name: "Veg. Noodle (Full)", price: 70 },
        { name: "Paneer Noodle (Half)", price: 90 },
        { name: "Paneer Noodle (Full)", price: 130 },
        { name: "Egg Noodle (Half)", price: 70 },
        { name: "Egg Noodle (Full)", price: 100 },
        { name: "Chilli Chicken (Half)", price: 140 },
        { name: "Chilli Chicken (Full)", price: 260 },
        { name: "Chicken Noodle (Half)", price: 90 },
        { name: "Chicken Noodle (Full)", price: 130 }
    ],
    "French Fries": [
        { name: "Masala French Fries (Half)", price: 50 },
        { name: "Masala French Fries (Full)", price: 80 },
        { name: "Peri Peri French Fries (Half)", price: 70 },
        { name: "Peri Peri French Fries (Full)", price: 100 },
        { name: "Makhni French Fries (Half)", price: 80 },
        { name: "Makhni French Fries (Full)", price: 120 },
        { name: "Cheesy French Fries (Half)", price: 80 },
        { name: "Cheesy French Fries (Full)", price: 120 }
    ],
    "Roti": [
        { name: "Rumali Roti", price: 10 },
        { name: "Tawa Roti", price: 10 },
        { name: "Tandoori Roti", price: 10 },
        { name: "Lachha Pratha", price: 30 },
        { name: "Butter Naan", price: 30 },
        { name: "Garlic Naan", price: 50 },
        { name: "Aloo Masala Naan", price: 50 },
        { name: "Stuff Naan", price: 80 },
        { name: "Aloo Pratha", price: 50 },
        { name: "Piyaz Pratha", price: 50 },
        { name: "Gobhi Pratha", price: 50 },
        { name: "Paneer Pratha", price: 80 },
        { name: "Stuffed Pratha", price: 90 },
        { name: "Chicken Pratha", price: 100 }
    ],
    "Main Course Veg": [
        { name: "Dal Fry (Quarter)", price: 70 },
        { name: "Dal Fry (Half)", price: 100 },
        { name: "Dal Fry (Full)", price: 150 },
        { name: "Aloo Jeera (Quarter)", price: 70 },
        { name: "Aloo Jeera (Half)", price: 100 },
        { name: "Aloo Jeera (Full)", price: 150 },
        { name: "Dal Makhni (Quarter)", price: 100 },
        { name: "Dal Makhni (Half)", price: 150 },
        { name: "Dal Makhni (Full)", price: 200 },
        { name: "Paneer Butter Masala (Quarter)", price: 110 },
        { name: "Paneer Butter Masala (Half)", price: 170 },
        { name: "Paneer Butter Masala (Full)", price: 230 },
        { name: "Kadai Paneer (Quarter)", price: 110 },
        { name: "Kadai Paneer (Half)", price: 170 },
        { name: "Kadai Paneer (Full)", price: 230 },
        { name: "Shahi Paneer (Quarter)", price: 110 },
        { name: "Shahi Paneer (Half)", price: 170 },
        { name: "Shahi Paneer (Full)", price: 230 },
        { name: "Matar Paneer (Quarter)", price: 110 },
        { name: "Matar Paneer (Half)", price: 170 },
        { name: "Matar Paneer (Full)", price: 230 },
        { name: "Paneer Bhuna Masala (Quarter)", price: 130 },
        { name: "Paneer Bhuna Masala (Half)", price: 190 },
        { name: "Paneer Bhuna Masala (Full)", price: 250 },
        { name: "Chaap Butter Masala (Quarter)", price: 80 },
        { name: "Chaap Butter Masala (Half)", price: 130 },
        { name: "Chaap Butter Masala (Full)", price: 180 },
        { name: "Chaap Bhuna Masala (Quarter)", price: 80 },
        { name: "Chaap Bhuna Masala (Half)", price: 130 },
        { name: "Chaap Bhuna Masala (Full)", price: 180 },
        { name: "Kadai Chaap (Quarter)", price: 80 },
        { name: "Kadai Chaap (Half)", price: 130 },
        { name: "Kadai Chaap (Full)", price: 180 },
        { name: "Bhoondi Raita (Quarter)", price: 50 },
        { name: "Bhoondi Raita (Half)", price: 80 },
        { name: "Bhoondi Raita (Full)", price: 100 }
    ],
    "Main Course Non-Veg": [
        { name: "Butter Chicken (Quarter)", price: 110 },
        { name: "Butter Chicken (Half)", price: 170 },
        { name: "Butter Chicken (Full)", price: 280 },
        { name: "Kadai Chicken (Quarter)", price: 110 },
        { name: "Kadai Chicken (Half)", price: 170 },
        { name: "Kadai Chicken (Full)", price: 280 },
        { name: "Chicken Bhuna (Quarter)", price: 130 },
        { name: "Chicken Bhuna (Half)", price: 200 },
        { name: "Chicken Bhuna (Full)", price: 320 },
        { name: "Chicken Korma (Quarter)", price: 110 },
        { name: "Chicken Korma (Half)", price: 170 },
        { name: "Chicken Korma (Full)", price: 280 },
        { name: "Chicken Rara (Quarter)", price: 140 },
        { name: "Chicken Rara (Half)", price: 210 },
        { name: "Chicken Rara (Full)", price: 340 },
        { name: "Egg Butter Masala (Quarter)", price: 70 },
        { name: "Egg Butter Masala (Half)", price: 100 },
        { name: "Egg Butter Masala (Full)", price: 150 },
        { name: "Egg Bhuna Masala (Quarter)", price: 80 },
        { name: "Egg Bhuna Masala (Half)", price: 120 },
        { name: "Egg Bhuna Masala (Full)", price: 180 },
        { name: "Egg Kadai Masala (Quarter)", price: 70 },
        { name: "Egg Kadai Masala (Half)", price: 100 },
        { name: "Egg Kadai Masala (Full)", price: 150 }
    ]
};

const addonMap = {
    "1": { name: "Mayonise", price: 10 },
    "2": { name: "Tandoor Mayonise", price: 10 },
    "3": { name: "Schzwan Saus", price: 10 },
    "4": { name: "Amul Butter", price: 10 },
    "5": { name: "Egg", price: 20 },
    "6": { name: "Dbl. Egg", price: 30 },
    "7": { name: "Cheese Spread", price: 20 },
    "8": { name: "Cheese Slice", price: 20 },
    "9": { name: "Wheat Base", price: 0 }
};

module.exports = { menuData, addonMap };
